######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 1 15:37:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Serial.h CommPort.h Ergomo.h Ride.h
SOURCES += Serial.cpp main.cpp CommPort.cpp Ergomo.cpp Ride.cpp
